In [2]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[8,9]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [8, 9]]])

In [5]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.random.random((4,3))

array([[0.53158499, 0.05393221, 0.33294961],
       [0.41483905, 0.02913489, 0.09170517],
       [0.77753146, 0.21443201, 0.07098112],
       [0.48531948, 0.21707408, 0.84128123]])

In [11]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [12]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# array attributes

In [13]:
a = np.arange(10, dtype= np.int32)
b = np.arange(12, dtype=float).reshape(4,3)
c = np.arange(8).reshape(2,2,2)

In [14]:
print(a.ndim)
print(b.shape)
print(c.shape)

1
(4, 3)
(2, 2, 2)


In [15]:
print(a.size)
print(b.size)
print(c.size)

10
12
8


In [16]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

4
8
4


In [17]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int32


changing datatype

In [18]:
b.astype(np.int32)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# array operation

In [19]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

scalar operation

In [20]:
#arithmatic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [21]:
#relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

vector operation

In [22]:
#arithmatic 
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# numpy array functions

In [23]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[33., 30., 32.],
       [82., 90., 33.],
       [76.,  4., 15.]])

In [24]:
np.max(a1)

90.0

In [25]:
np.min(a1)

4.0

In [26]:
np.sum(a1, axis=1)

array([ 95., 205.,  95.])

In [27]:
np.prod(a1, axis=0)

array([205656.,  10800.,  15840.])

In [28]:
np.mean(a1,axis=0)

array([63.66666667, 41.33333333, 26.66666667])

In [29]:
np.median(a1,axis=0)

array([76., 30., 32.])

In [30]:
np.std(a1,axis=0)

array([21.8225164 , 36.01234356,  8.25967446])

In [31]:
np.var(a1,axis=0)

array([ 476.22222222, 1296.88888889,   68.22222222])

In [32]:
np.sin(a1)

array([[ 0.99991186, -0.98803162,  0.55142668],
       [ 0.31322878,  0.89399666,  0.99991186],
       [ 0.56610764, -0.7568025 ,  0.65028784]])

In [33]:
# dot product 
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [34]:
# log and exponents
np.log(a1)

array([[3.49650756, 3.40119738, 3.4657359 ],
       [4.40671925, 4.49980967, 3.49650756],
       [4.33073334, 1.38629436, 2.7080502 ]])

In [35]:
np.exp(a1)

array([[2.14643580e+14, 1.06864746e+13, 7.89629602e+13],
       [4.09399696e+35, 1.22040329e+39, 2.14643580e+14],
       [1.01480039e+33, 5.45981500e+01, 3.26901737e+06]])

In [36]:
np.round(np.random.random((2,3))*100)

array([[80., 18., 51.],
       [91., 92., 99.]])

In [37]:
np.floor(np.random.random((2,3))*100)

array([[53., 83., 76.],
       [39., 23., 10.]])

In [38]:
np.ceil(np.random.random((2,3))*100)

array([[76., 14., 22.],
       [15.,  9., 76.]])

# indexing and slicing

In [39]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [40]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1[-1]

9

In [42]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a2[1,2]

6

In [44]:
a2[2,3]

11

In [45]:
a2[1,0]

4

In [46]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [47]:
a3[1,0,1]

5

In [48]:
a3[0,1,0]

2

In [49]:
a3[0,0,0]

0

In [50]:
a3[1,1,0]

6

In [51]:
#slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a1[2:5]

array([2, 3, 4])

In [53]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [55]:
a2[0,:]

array([0, 1, 2, 3])

In [56]:
a2[:,2]

array([ 2,  6, 10])

In [57]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [58]:
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [59]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [60]:
a2[1,0::3]

array([4, 7])

In [61]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [62]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [63]:
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [64]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [65]:
a3[1,:,1]

array([10, 13, 16])

In [66]:
a3[0,1,:]

array([3, 4, 5])

In [67]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [68]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

iterating

In [70]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [72]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [73]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [74]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [77]:
np.transpose(a1)
a1.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [79]:
a3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [81]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [85]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [86]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [88]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

# advance numpy

In [1]:
# spped
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c = []
import time 
start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

6.576291561126709


In [3]:
import numpy as np
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
start = time.time()
c = a+b
print(time.time()-start)

3.7987239360809326


In [4]:
#memory 
a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [7]:
a = np.arange(10000000, dtype=np.int8)
sys.getsizeof(a)

10000104